"""role

Revision ID: 14b07dffae43
Revises: ab3802c07181
Create Date: 2020-04-25 10:19:29.835422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b07dffae43'
down_revision = 'ab3802c07181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('regular_user', 'editor', 'admin', name='roleenum'), nullable=True))
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.drop_index('ix_user_is_admin', table_name='user')
    op.drop_index('ix_user_is_editor', table_name='user')
    op.drop_column('user', 'is_editor')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_editor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_is_editor', 'user', ['is_editor'], unique=False)
    op.create_index('ix_user_is_admin', 'user', ['is_admin'], unique=False)
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
