"""comments

Revision ID: 3f6434700142
Revises: 26e74dcefde1
Create Date: 2020-05-01 22:23:28.305163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6434700142'
down_revision = '26e74dcefde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_model_comment_date'), 'comment_model', ['comment_date'], unique=False)
    op.create_index(op.f('ix_comment_model_comment_text'), 'comment_model', ['comment_text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_model_comment_text'), table_name='comment_model')
    op.drop_index(op.f('ix_comment_model_comment_date'), table_name='comment_model')
    op.drop_table('comment_model')
    # ### end Alembic commands ###
