"""empty message

Revision ID: 5d828a99f77f
Revises: 0b631c28dad9
Create Date: 2020-04-20 10:36:28.842580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d828a99f77f'
down_revision = '0b631c28dad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_is_admin', table_name='user')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_user_is_admin', 'user', ['is_admin'], unique=False)
    # ### end Alembic commands ###
