"""empty message

Revision ID: 69470de37505
Revises: 2280b3e6490a
Create Date: 2020-04-24 20:55:09.932061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69470de37505'
down_revision = '2280b3e6490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_user'), 'user', ['is_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_user'), table_name='user')
    op.drop_column('user', 'is_user')
    # ### end Alembic commands ###
