"""empty message

Revision ID: 941d2c4008f8
Revises: 5d828a99f77f
Create Date: 2020-04-20 10:39:25.081664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941d2c4008f8'
down_revision = '5d828a99f77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_is_admin'), 'user', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_admin'), table_name='user')
    # ### end Alembic commands ###
