"""empty message

Revision ID: 9630dd0fb6f3
Revises: fff23736b493
Create Date: 2020-04-27 21:57:29.842755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9630dd0fb6f3'
down_revision = 'fff23736b493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_post_model', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image_post_model', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_post_model', type_='foreignkey')
    op.drop_column('image_post_model', 'user_id')
    # ### end Alembic commands ###
