"""empty message

Revision ID: ab3802c07181
Revises: 69470de37505
Create Date: 2020-04-24 20:56:45.134269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3802c07181'
down_revision = '69470de37505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_editor', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_editor'), 'user', ['is_editor'], unique=False)
    op.drop_index('ix_user_is_user', table_name='user')
    op.drop_column('user', 'is_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_is_user', 'user', ['is_user'], unique=False)
    op.drop_index(op.f('ix_user_is_editor'), table_name='user')
    op.drop_column('user', 'is_editor')
    # ### end Alembic commands ###
