"""choices

Revision ID: c4c99e5c0b57
Revises: c676ccf057d3
Create Date: 2020-04-25 10:32:21.578869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from flask_web_app.models import ChoiceType

# revision identifiers, used by Alembic.
revision = 'c4c99e5c0b57'
down_revision = 'c676ccf057d3'
branch_labels = None
depends_on = None

genero = {
    'nulo': "--",
    'hombre': "Hombre",
    'mujer': "Mujer"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=postgresql.ENUM('nulo', 'hombre', 'mujer', name='genderderenum'),
               type_=ChoiceType(genero),
               existing_nullable=True)
    op.drop_index('ix_user_is_editor', table_name='user')
    op.drop_column('user', 'is_editor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_editor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_is_editor', 'user', ['is_editor'], unique=False)
    op.alter_column('user', 'gender',
               existing_type=ChoiceType(genero),
               type_=postgresql.ENUM('nulo', 'hombre', 'mujer', name='genderderenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
