"""choices

Revision ID: c676ccf057d3
Revises: 14b07dffae43
Create Date: 2020-04-25 10:31:02.890840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from flask_web_app.models import ChoiceType

# revision identifiers, used by Alembic.
revision = 'c676ccf057d3'
down_revision = '14b07dffae43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=postgresql.ENUM('nulo', 'hombre', 'mujer', name='genderderenum'),
               type_=ChoiceType(),
               existing_nullable=True)
    op.drop_index('ix_user_is_admin', table_name='user')
    op.drop_index('ix_user_is_editor', table_name='user')
    op.drop_column('user', 'is_editor')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_editor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_is_editor', 'user', ['is_editor'], unique=False)
    op.create_index('ix_user_is_admin', 'user', ['is_admin'], unique=False)
    op.alter_column('user', 'gender',
               existing_type=flask_web_app.models.ChoiceType(),
               type_=postgresql.ENUM('nulo', 'hombre', 'mujer', name='genderderenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
