"""empty message

Revision ID: e032cee1827b
Revises: ef534dc6a6e3
Create Date: 2020-04-22 08:48:04.721179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e032cee1827b'
down_revision = 'ef534dc6a6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_model_title', table_name='post_model')
    op.create_index(op.f('ix_post_model_title'), 'post_model', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_model_title'), table_name='post_model')
    op.create_index('ix_post_model_title', 'post_model', ['title'], unique=False)
    # ### end Alembic commands ###
