"""empty message

Revision ID: e142077133aa
Revises: 8dd048c7ff31
Create Date: 2020-04-24 10:27:44.582773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e142077133aa'
down_revision = '8dd048c7ff31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_post_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_post_model_path'), 'image_post_model', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_post_model_path'), table_name='image_post_model')
    op.drop_table('image_post_model')
    # ### end Alembic commands ###
