"""primera migracion

Revision ID: ef534dc6a6e3
Revises: 
Create Date: 2020-04-21 18:54:19.393633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef534dc6a6e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('hombre', 'mujer', name='genderderenum'), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_avatar'), 'user', ['avatar'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_information'), 'user', ['information'], unique=False)
    op.create_index(op.f('ix_user_is_admin'), 'user', ['is_admin'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('post_modified', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_model_post_date'), 'post_model', ['post_date'], unique=False)
    op.create_index(op.f('ix_post_model_post_modified'), 'post_model', ['post_modified'], unique=False)
    op.create_index(op.f('ix_post_model_post_text'), 'post_model', ['post_text'], unique=False)
    op.create_index(op.f('ix_post_model_title'), 'post_model', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_model_title'), table_name='post_model')
    op.drop_index(op.f('ix_post_model_post_text'), table_name='post_model')
    op.drop_index(op.f('ix_post_model_post_modified'), table_name='post_model')
    op.drop_index(op.f('ix_post_model_post_date'), table_name='post_model')
    op.drop_table('post_model')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_is_admin'), table_name='user')
    op.drop_index(op.f('ix_user_information'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_avatar'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
